# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

reviews:
  commit_status: false
  review_status: false
  auto_review:
    ignore_title_keywords:
      - "[skip ci]"
    ignore_usernames:
      - "github-actions[bot]"
