package ch.fmartin.symphony.trello.setup;

/// How one workflow body relates to the generated bodies of the installed and the target Symphony
/// version. See ADR 0095 and `SPEC.md` Section 19.4.1.
enum WorkflowBodyClassification {
    /// The source and target versions generate the same body, so there is nothing to migrate.
    NO_GENERATED_BODY_CHANGE(Action.NONE),
    /// The body already contains the target generated body exactly once.
    ALREADY_CURRENT(Action.NONE),
    /// The complete body equals the source generated body.
    UNCHANGED_GENERATED_BODY(Action.REPLACE),
    /// The source generated body occurs exactly once, with user text only before and/or after it.
    USER_PREFIX_SUFFIX(Action.REPLACE),
    /// The source generated body was edited, reordered, or partly removed.
    INTERNALLY_CUSTOMIZED(Action.MANUAL),
    /// The source generated body occurs more than once.
    DUPLICATE_GENERATED_BODY(Action.MANUAL),
    /// No recorded source body, and the body does not contain the target body.
    UNKNOWN_SOURCE(Action.MANUAL),
    /// The workflow cannot be read, parsed, or safely written.
    MALFORMED(Action.MANUAL),
    /// The workflow was generated by a newer major version than the one running.
    UNSUPPORTED_MAJOR_DOWNGRADE(Action.REJECT);

    private final Action action;

    WorkflowBodyClassification(Action action) {
        this.action = action;
    }

    Action action() {
        return action;
    }

    enum Action {
        NONE,
        REPLACE,
        MANUAL,
        REJECT
    }
}
