import {spawnSync} from "node:child_process";
import {chmodSync, copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync} from "node:fs";
import {homedir} from "node:os";
import {join} from "node:path";
import type {RunRoot} from "./run-root.ts";
import {runCommand} from "./symphony.ts";

/** Behaviors understood by scripts/FakeCodexAppServer.java, one per script line. */
export type FakeCodexStep =
  | {kind: "tool"; tool: string; arguments: Record<string, unknown>}
  | {kind: "user-input"}
  | {kind: "approval"; method: string}
  | {kind: "telemetry"}
  | {kind: "malformed-json"}
  | {kind: "turn-cancelled"}
  | {kind: "stall"}
  | {kind: "handoff"}
  | {kind: "complete"};

export interface FakeCodex {
  /** Value for `codex.command` in a run-scoped workflow. */
  command: string;
  promptDir: string;
  toolDir: string;
  scriptDir: string;
}

export interface ToolResponse {
  scenario: string;
  request: string;
  response: string;
}

/**
 * Writes a run-scoped launcher for the deterministic Java fake app-server. Each fixture gets its own
 * prompt log, tool log, and script directory, so scenarios can assert on the prompt Symphony sent and
 * on the client's answers to scripted tool calls.
 */
export function fakeCodex(
  run: RunRoot,
  fixture: string,
  options: {reviewList?: string; sleepMs?: number} = {},
): FakeCodex {
  const base = run.dir("fakes", "codex", fixture);
  const classes = compiledFakeCodex(run);
  const scriptDir = run.dir("fakes", "codex", fixture, "scripts");
  const evidence = run.dir("private-evidence", fixture);
  const promptDir = join(evidence, "fake-codex-prompts");
  const toolDir = join(evidence, "fake-codex-tool-responses");
  // A resumed run reuses fixture directories; start from empty records and scripts.
  for (const directory of [promptDir, toolDir, scriptDir]) {
    rmSync(directory, {recursive: true, force: true});
    mkdirSync(directory, {recursive: true});
  }
  const launcher = join(base, "fake-codex-app-server.sh");
  const java = javaExecutable();
  writeFileSync(
    launcher,
    [
      "#!/usr/bin/env bash",
      "# Generated by scripts/live-bugbash for one run-scoped fixture.",
      `export SYMPHONY_FAKE_CODEX_PROMPT_DIR=${shellQuote(promptDir)}`,
      `export SYMPHONY_FAKE_CODEX_TOOL_DIR=${shellQuote(toolDir)}`,
      `export SYMPHONY_FAKE_CODEX_SCRIPT_DIR=${shellQuote(scriptDir)}`,
      `export SYMPHONY_FAKE_CODEX_REVIEW_STATE=${shellQuote(options.reviewList ?? "Human Review")}`,
      `export SYMPHONY_FAKE_CODEX_SLEEP_MS=${options.sleepMs ?? 0}`,
      // The script directory argument is ignored by the fake; it lets cleanup and scenarios tell
      // fixtures apart by command line.
      `exec ${shellQuote(java)} -cp ${shellQuote(classes)} FakeCodexAppServer ${shellQuote(scriptDir)}`,
      "",
    ].join("\n"),
  );
  chmodSync(launcher, 0o755);
  return {command: launcher, promptDir, toolDir, scriptDir};
}

/** Compiles scripts/FakeCodexAppServer.java once per run so each fake turn starts quickly. */
function compiledFakeCodex(run: RunRoot): string {
  const classes = run.path("fakes", "codex", "classes");
  const source = join(run.repoRoot, "scripts", "FakeCodexAppServer.java");
  const compiled = join(classes, "FakeCodexAppServer.class");
  if (!existsSync(compiled) || statSync(compiled).mtimeMs < statSync(source).mtimeMs) {
    mkdirSync(classes, {recursive: true});
    const javac = javaExecutable().replace(/java$/, "javac");
    const result = spawnSync(javac, ["--release", "25", "-d", classes, source], {
      encoding: "utf8",
    });
    if (result.status !== 0) {
      throw new Error(`could not compile the fake Codex app-server: ${result.stderr}`);
    }
  }
  return classes;
}

export function writeFakeCodexScript(codex: FakeCodex, scenarioId: string, steps: readonly FakeCodexStep[]): void {
  const lines = steps.map((step) => {
    switch (step.kind) {
      case "tool":
        return `tool ${step.tool} ${JSON.stringify(step.arguments)}`;
      case "approval":
        return `approval ${step.method}`;
      default:
        return step.kind;
    }
  });
  writeFileSync(join(codex.scriptDir, `${scenarioId}.script`), `${lines.join("\n")}\n`);
}

/** Records the fake app-servers wrote into one directory, oldest first. */
function records(directory: string): string[] {
  if (!existsSync(directory)) {
    return [];
  }
  return readdirSync(directory)
    .filter((name) => name.endsWith(".txt"))
    .sort()
    .map((name) => readFileSync(join(directory, name), "utf8"));
}

/** Prompts captured from `turn/start` requests, oldest first. */
export function capturedPrompts(codex: FakeCodex): string[] {
  return records(codex.promptDir).map((line) => {
    const request = JSON.parse(line) as {params?: {input?: Array<{text?: string}>}};
    return (request.params?.input ?? []).map((item) => item.text ?? "").join("\n");
  });
}

export function promptsMentioning(codex: FakeCodex, marker: string): string[] {
  return capturedPrompts(codex).filter((prompt) => prompt.includes(marker));
}

export function toolResponses(codex: FakeCodex, scenarioId: string): ToolResponse[] {
  return records(codex.toolDir)
    .filter((record) => record.startsWith(`${scenarioId}\t`))
    .map((record) => {
      const [scenario = "", request = "", ...response] = record.split("\t");
      return {scenario, request, response: response.join("\t")};
    });
}

export function codexAvailable(): boolean {
  return spawnSync("codex", ["--version"], {encoding: "utf8", timeout: 20_000}).status === 0;
}

/**
 * Creates a run-scoped CODEX_HOME holding only a copy of the operator's Codex auth file, so real
 * Codex runs never write sessions or history into the normal Codex home. The copy is registered as
 * sensitive and deleted by cleanup.
 */
export function runScopedCodexHome(run: RunRoot): string {
  const source = operatorCodexAuth();
  const home = run.dir("state", "codex-home");
  if (existsSync(source)) {
    copyFileSync(source, join(home, "auth.json"));
    chmodSync(join(home, "auth.json"), 0o600);
  }
  run.registerSensitivePath(home);
  return home;
}

function operatorCodexAuth(): string {
  return join(process.env["CODEX_HOME"] ?? join(homedir(), ".codex"), "auth.json");
}

/**
 * True when Codex rewrote the run's auth copy, for example after refreshing its login. The harness
 * never writes to the operator's Codex home, so cleanup reports this instead of copying it back.
 */
export function runCodexAuthChanged(run: RunRoot): boolean {
  const copy = run.path("state", "codex-home", "auth.json");
  const source = operatorCodexAuth();
  return existsSync(copy) && existsSync(source) && readFileSync(copy, "utf8") !== readFileSync(source, "utf8");
}

export interface SentinelResult {
  ok: boolean;
  detail: string;
}

/**
 * Asks real Codex to append one line to a run-owned marker file and checks that the marker changed.
 * Bounded by `timeoutMs`; uses the workspace-write sandbox with the marker directory as the
 * workspace, so no host path outside the run is writable.
 */
export async function realCodexSentinel(run: RunRoot, scenarioId: string, timeoutMs: number): Promise<SentinelResult> {
  const directory = run.dir("workspaces", "codex-sentinel", scenarioId);
  mkdirSync(directory, {recursive: true});
  const marker = join(directory, "sentinel.txt");
  writeFileSync(marker, "start\n");
  const line = `sentinel ${run.runId} ${Date.now()}`;
  const result = await runCommand(
    "codex",
    [
      "exec",
      "--skip-git-repo-check",
      "--sandbox",
      "workspace-write",
      "-C",
      directory,
      `Append exactly one line with the text "${line}" to the file sentinel.txt in the current directory. Do not touch anything else and do not run any other command.`,
    ],
    {timeoutMs, env: {...process.env, CODEX_HOME: runScopedCodexHome(run)}, cwd: directory},
  );
  run.privateEvidence(scenarioId, "codex-sentinel.log", `${result.stdout}\n--- stderr ---\n${result.stderr}`);
  const changed = readFileSync(marker, "utf8").includes(line);
  if (result.timedOut) {
    return {ok: false, detail: `codex exec did not finish within ${Math.round(timeoutMs / 1000)}s`};
  }
  return changed
    ? {ok: true, detail: "codex exec appended the sentinel line"}
    : {ok: false, detail: `codex exec exited ${result.status} without changing the sentinel`};
}

export function javaExecutable(): string {
  const javaHome = process.env["JAVA_HOME"];
  return javaHome !== undefined && existsSync(join(javaHome, "bin", "java")) ? join(javaHome, "bin", "java") : "java";
}

export function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'"'"'`)}'`;
}
