name: Dependency Submission

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'pom.xml'
      - '.github/workflows/dependency-submission.yml'
      - '.mvn/jvm.config'

permissions: read-all

jobs:
  dependency-submission:
    if: >-
      ${{ !startsWith(github.head_ref, 'release-please--branches--')
      && github.head_ref != 'renovate/openrewrite-toolchain'
      && !startsWith(github.head_ref, 'automation/openrewrite/renovate-') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5
        with:
          distribution: temurin
          java-version: "25"
          cache: maven
      - name: Submit Dependencies
        uses: advanced-security/maven-dependency-submission-action@b275d12641ac2d2108b2cbb7598b154ad2f2cee8 # v5.0.0
